### ISSUE TITLE
AU 005-1-invalid-au appears to be making non-conformant call to agent profile

### ISSUE THREAD

**Issue by cawerkenthin** [adlnet/CATAPULT#35]
In execution of 005-1-invalid-au, a call is made to the agent profile API.  The call does not include an agent and is rejected by the LRS, making it impossible to complete the test.

Call  is made to:
 lrs_endpoint//agents/profile?profileId=cmi5LearnerPreferences

Note: Not a typo, the call has two slashes.

Payload is:
{languagePreference: "en-US,fr-FR,fr-BE", audioPreference: "on"}

Our version was downloaded 12/9/21.  Is there a newer version?

**Comment by brianjmiller** [comment]
The lack of an `agent` parameter is intentional. The request is used to verify

> 11.0.0.0-1
> The Agent used in xAPI Agent Profile requests MUST match the actor property generated by the LMS at AU launch time.

And is verifying that the LRS returns a 400 status code (bad request). There is a newer version, latest is Jan 28, and I believe prior to this the status codes were either not checked or checked differently. See history at:

https://github.com/adlnet/CATAPULT/commits/main/lts/pkg/src/005-1-invalid-au/005-1-invalid-au.js

**Comment by cawerkenthin** [comment]
Thanks @brianjmiller, we will try out the newer version.
